### ISSUE TITLE
should use ctx.response.remove for useless keys

### ISSUE THREAD

**Issue by Maxwin-z** [chinesedfan/parrot-mocker-web#10]
```
response.remove(field)

// Remove header field.
```

[https://github.com/chinesedfan/parrot-mocker-web/blob/master/server/api/rewrite.js#L115-L118](https://github.com/chinesedfan/parrot-mocker-web/blob/master/server/api/rewrite.js#L115-L118)
```
            // trust kcors to handle these headers
            if (k === 'access-control-allow-origin' || k === 'access-control-allow-credentials') return;
            // no encoding
            if (k === 'content-encoding') return;
```

**Comment by chinesedfan** [comment]
Here I need to extract response headers from `node-fetch`, and save in `koa` context.

Using `ctx.response.set(fields)` and `ctx.response.remove(field)` is a simple way. But `node-fetch` provides no public API(`res.headers.raw() is non-spec`) for getting all header fields as a plain object.
