### ISSUE TITLE
Add examples of pathType/responseType

### ISSUE THREAD

**Issue by AimLuo** [chinesedfan/parrot-mocker-web#15]
能否说下图中pathType和responseType的使用示例。自己试了下，没效果。
![image](https://user-images.githubusercontent.com/21124342/30841029-091c78f0-a240-11e7-98fe-b8da6d0b4379.png)

**Comment by chinesedfan** [comment]
@AimLuo 请问你使用的是本地部署的，还是leancloud的？

抱歉leancloud我忘记更新部署了，这几个选项是后来支持的，刚刚重新部署。

**Comment by AimLuo** [comment]
我是直接clone到本地的，webpack打包后，PORT=8001 node app.js，配合插件劫持数据到http://127.0.0.1:8001/

**Comment by chinesedfan** [comment]
@AimLuo 我在文档里添加了几个示例，请你看下是否明白。如果还有问题，可以把你的config贴上来。
