### ISSUE TITLE
No client id is found

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [chinesedfan/parrot-mocker-web#28]

**Comment by chinesedfan** [comment]
Any error output or detailed description? Sorry, I don't understand your problem.

**Comment by sprlwrksAprilmintacpineda** [comment]
@chinesedfan I installed the extension. I created a simple nodejs server. I then started the nodejs server. I clicked on the extension and pasted the link there, I got this --->

![image](https://user-images.githubusercontent.com/39720421/46386445-11ef1080-c6f4-11e8-9a44-415f6ebf4201.png)

**Comment by sprlwrksAprilmintacpineda** [comment]
@chinesedfan how do I know that a client id has been created?

**Comment by chinesedfan** [comment]
@sprlwrksAprilmintacpineda There are several ways, i.e.
- the website shows at the top area
- the extension no longer warns about "No client id"
