### ISSUE TITLE
一直显示404连不上mock

### ISSUE THREAD

**Issue by guanqinge** [chinesedfan/parrot-mocker-web#30]
按照步骤操作了，但是在我的电脑就是一直跑不起来
![image](https://user-images.githubusercontent.com/42338258/67471361-dec24b00-f681-11e9-91ce-c3c38c1cbd81.png)
![image](https://user-images.githubusercontent.com/42338258/67471399-eda8fd80-f681-11e9-90d8-2737c9e6f530.png)

**Comment by chinesedfan** [comment]
> Not support:
relative or local DNS parsed requests, because the mock server can not resolve them

因为是转发，所以需要mock服务器能访问的请求才能被转发；但是你依然可以使用mock功能。
