### ISSUE TITLE
not support xhr('/path', ...)?

### ISSUE THREAD

**Issue by Maxwin-z** [chinesedfan/parrot-mocker-web#9]
In the xhr.open wrap code 
```
 ...
 var parsedUrl = url.parse(urlStr, true, true);
 // do not forward relative or local request, beacuse the server can not resolve
 if (!parsedUrl.host) return urlStr;
 ...
```

If urlStr is `/path` like (without host), the wrap will fail.

**Comment by chinesedfan** [comment]
Right. Just like the comment says, the mock server can not resolve the host correctly. Users may modify their hosts file, or visit a website of private networks.

**Comment by chinesedfan** [comment]
Refer to https://github.com/chinesedfan/parrot-mocker/pull/4.
